version: '3.8'

services:
  postgres1:
    image: postgres:16.3-alpine3.20
    container_name: clientes
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data

  postgres2:
    image: postgres:16.3-alpine3.20
    container_name: produtos
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: products_db
    ports:
      - "5433:5432"
    volumes:
      - postgres2_data:/var/lib/postgresql/data

  postgres3:
    image: postgres:16.3-alpine3.20
    container_name: pedidos
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: requests_db
    ports:
      - "5434:5432"
    volumes:
      - postgres3_data:/var/lib/postgresql/data

  postgres4:
    image: postgres:16.3-alpine3.20
    container_name: entregas
    environment:
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
      POSTGRES_DB: deliveries_db
    ports:
      - "5435:5432"
    volumes:
      - postgres4_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres1_data:
  postgres2_data:
  postgres3_data:
  postgres4_data:
  rabbitmq_data:
