server:
  port: 8081

spring:
  application:
    name: msclientes
  datasource:
    url: jdbc:postgresql://localhost:5432/clients_db
    username: user1
    password: password1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    function:
      web:
        path: /api